###
POST http://localhost:9000/api/user HTTP/1.1
Content-Type: application/json

{
    "firstName": "Macarena",
    "lastName": "Cousillas",
    "mail": "mcousillas@correo.um.edu.uy",
    "isStudent": false,
    "subjects": ["1"]
}

###
GET http://localhost:9000/api/users HTTP/1.1
###
GET http://localhost:9000/api/user/62bd994203e08c3fb067738c HTTP/1.1
###
PUT http://localhost:9000/api/user/62bd994203e08c3fb067738c HTTP/1.1
Content-Type: application/json

{
    "firstName": "Josefina",
    "lastName": "Gallinal",
    "mail": "jmgallinal@correo.um.edu.uy",
    "isStudent": false,
    "subjects": ["1", "3"]
}

###
DELETE http://localhost:9000/api/user/62bd9e6652bdd153ef9b4ac0 HTTP/1.1

###
GET http://localhost:9000/api/userByMail/jmgallinal@correo.um.edu.uy HTTP/1.1

###
POST http://localhost:9000/api/claim HTTP/1.1
Content-Type: application/json

{
    "title": "Enchufe salón L202 roto",
    "message": "El enchufe del salón L202 está roto. Se salió del piso y puede causa accidentes.",
    "userMail": "pgarcia4@correo.um.edu.uy"
}
###
GET http://localhost:9000/api/claims HTTP/1.1

###
POST http://localhost:9000/api/user HTTP/1.1
Content-Type: application/json

{
    "firstName": "Florencia",
    "lastName": "Migues",
    "password": "12345678",
    "mail": "fmigues@correo.um.edu.uy",
    "isStudent": false,
    "subjects": ["1"]
}

###
POST  http://localhost:9000/login HTTP/1.1
Content-Type: application/json

{
    "mail": "fmigues@correo.um.edu.uy",
    "password": "12345678"
}

###
POST http://localhost:9000/api/newGrid HTTP/1.1
Content-Type: application/json

{
    "plan": "2022",
    "carreer": "Ingenieria en informatica",
    "link": "https://drive.google.com/uc?export=download&id=11YQvQS0KheqkMnt0qs0x_fxgVRAULo_X"
}

###
POST http://localhost:9000/api/newGrid HTTP/1.1
Content-Type: application/json

{
    "plan": "2022",
    "carreer": "INFO",
    "link": "https://drive.google.com/uc?export=download&id=11YQvQS0KheqkMnt0qs0x_fxgVRAULo_X"
}

###
GET http://localhost:9000/api/grid/2022/INFO HTTP/1.1

###
GET http://localhost:9000/api/userByMail/fmigues@correo.um.edu.uy HTTP/1.1
